
services:
  # TODO: Add pgbouncer
  postgres:
    image: postgres:16.3-alpine3.20 
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - "/var/lib/postgresql/data"
  nats:
    image: nats:2.10.18-alpine3.20
    command:
     - "-js"
    ports:
     - 4222:4222
  minio:
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z
    ports:
      - 9001:9000
      - 9002:9001
    command: server --console-address ":9001" /data
    volumes:
      - "/data"
  # traefik:
  #   image: traefik:v3.1.2
  #   ports:
  #     - 443:443
    
networks:
  bridge:
