// Generated by Wrangler on Fri Aug 02 2024 20:38:31 GMT+0300 (Eastern European Summer Time)
// by running `wrangler types`

interface Env {
	IDENTITY_SERVER_LOGIN_ROUTE: "http://localhost:9000/api/identity/login";
	IDENTITY_SERVER_REFRESH_TOKEN_ROUTE: "http://localhost:9000/api/identity/refresh-access-token";
	IDENTITY_SERVER_LOGOUT_ROUTE: "http://localhost:9000/api/identity";
	PRODUCTS_ROUTE: "http://localhost:9000/api/products";
}
