name = "remix-cloudflare-workers-template"

main = "./server.js"
workers_dev = true
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"

[vars]
IDENTITY_SERVER_LOGIN_ROUTE = "http://localhost:9000/api/identity/login"
IDENTITY_SERVER_REFRESH_TOKEN_ROUTE =  "http://localhost:9000/api/identity/refresh-access-token"
IDENTITY_SERVER_LOGOUT_ROUTE = "http://localhost:9000/api/identity"
STRIPE_PUBLIC_KEY = "pk_test_..."

PRODUCTS_ROUTE = "http://localhost:9000/api/products"
CATALOGS_ROUTE = "http://localhost:9000/api/catalogs"
FRONT_PAGE_ROUTE = "http://localhost:9000/api/front-page"
CART_ROUTE = "http://localhost:9000/api/carts"
PAYMENT_ROUTE = "http://localhost:9000/api/payments"
ORDER_ROUTE = "http://localhost:9000/api/orders"
IMAGE_ROUTE = "http://localhost:9000/api/images"

[site]
bucket = "./build/client"

[build]
command = "npm run build"
